Use different search algorithm in `Strings::contains_any`
microsoft/vcpkg-tool pull request #1255
Opened 2023-10-28 22:22 UTC by Thomas1664

Using `std::boyer_moore_horspool_searcher` results in approx. 3x speedup of `Strings::contains_any` (observed during post build lint).

Note that this search algorithm is only useful when dealing with long strings: https://en.cppreference.com/w/cpp/utility/functional/boyer_moore_horspool_searcher

2023-10-28 22:54 UTC, Thomas1664 commented
Interestingly, `std::boyer_moore_horspool_searcher` is not available on OSX.

2023-10-30 21:37 UTC, BillyONeal commented on src/vcpkg/base/strings.cpp
> +            std::search(source.begin(), source.end(), boyer_moore_horspool_searcher(subject.begin(), subject.end()));
Creating the searcher should be hoist out of the loop

2023-10-30 22:16 UTC, BillyONeal commented on src/vcpkg/base/strings.cpp
> +            std::search(source.begin(), source.end(), boyer_moore_horspool_searcher(subject.begin(), subject.end()));
Nevermind I'm an idiot.

2023-10-30 22:22 UTC, BillyONeal commented on src/vcpkg/base/strings.cpp
> +            std::search(source.begin(), source.end(), boyer_moore_horspool_searcher(subject.begin(), subject.end()));
Although I do think this should be hoist to just after

```c++
auto files = fs.get_regular_files_recursive(dir, IgnoreErrors{});
```

in `postbuildlint.cpp`.

My concern is that `contains_any` looks like it's doing `contains`, not boyer_moore things, and I could easily see that being used in places boyer_moore would be inappropriate.

2023-10-30 22:34 UTC, BillyONeal requested changes
I either think `contains_any` should be renamed to indicate that it only makes sense for long haystacks now, and/or it should be given a `View<boyer_moore_horspool_searcher>` instead of the raw text.

2023-10-31 00:03 UTC, BillyONeal approved these changes

2023-10-31 00:23 UTC, merged

2023-10-31 00:23 UTC, BillyONeal commented
Thanks!

2023-11-04 01:04 UTC, autoantwort commented
I now get 467 warnings of the form 
```
/Users/leanderSchulten/git_projekte/vcpkg-tool/include/vcpkg/base/strings.h:51: warning: 'boyer_moore_horspool_searcher<std::__wrap_iter<const char *>>' is deprecated: std::experimental::boyer_moore_horspool_searcher will be removed in LLVM 17. Use std::boyer_moore_horspool_searcher instead [-Wdeprecated-declarations]
In file included from /Users/leanderSchulten/git_projekte/vcpkg-tool/src/vcpkg/base/hash.cpp:6:
/Users/leanderSchulten/git_projekte/vcpkg-tool/include/vcpkg/base/strings.h:51:62: warning: 'boyer_moore_horspool_searcher<std::__wrap_iter<const char *>>' is deprecated: std::experimental::boyer_moore_horspool_searcher will be removed in LLVM 17. Use std::boyer_moore_horspool_searcher instead [-Wdeprecated-declarations]
    using boyer_moore_horspool_searcher = std::experimental::boyer_moore_horspool_searcher<std::string::const_iterator>;
                                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/experimental/functional:341:7: note: 'boyer_moore_horspool_searcher<std::__wrap_iter<const char *>>' has been explicitly marked deprecated here
class _LIBCPP_DEPRECATED_BOYER_MOORE_HORSPOOL_SEARCHER _LIBCPP_TEMPLATE_VIS boyer_moore_horspool_searcher {
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/experimental/functional:90:60: note: expanded from macro '_LIBCPP_DEPRECATED_BOYER_MOORE_HORSPOOL_SEARCHER'
#  define _LIBCPP_DEPRECATED_BOYER_MOORE_HORSPOOL_SEARCHER _LIBCPP_DEPRECATED_("std::experimental::boyer_moore_horspool_searcher will be removed in LLVM 17. Use std::boyer_moore_horspool_searcher instead")
                                                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
```

2023-11-04 10:07 UTC, Thomas1664 commented
Honestly, I don't know what the best solution is. I could check for the feature test macro but then we don't get informed when we can remove this workaround.