[spdx] Fix copy-paste error
microsoft/vcpkg-tool pull request #1377
Opened 2024-04-02 19:12 UTC by Thomas1664

`github` was copied from above.

2024-04-15 22:57 UTC, ras0219-msft requested changes
Overall, I am really happy with the improvements in this PR! However, I think there's a few aspects of the implementation that need to be addressed.
 
This PR adds additional SPDX features but no SPDX tests. I'd like to see tests covering `vcpkg::run_resource_heuristics` for each of the new helpers. Adding tests to cover the existing `vcpkg_from_github` would be appreciated but not necessary :)

Additionally, can you please include a sample of SPDX documents before and after your change for a handful of ports, demonstrating that all changes were intentional and positive?

> Indexing of SPDXRef-resource started at 1

This is not a bug, unless you can reference an SPDX specification that indicates it should start at 0?

2024-04-15 22:57 UTC, ras0219-msft commented on src/vcpkg/cmake.cpp
> +        return Strings::replace_all(text, fmt::format("${{{}}}", var), value);
```suggestion
        return Strings::replace_all(text, std::string("${") + var + "}", value);
```
I think `fmt::format` is more obfuscating than clarifying here.

2024-04-15 22:57 UTC, ras0219-msft commented on include/vcpkg/cmake.h
> +    StringView find_cmake_invocation(StringView content, StringView command);
Given that these functions are _very much_ heuristics and only usable with caveats, I don't think they should be introduced as an independent "cmake" module. Instead, I think they should remain in spdx.cpp and exposed as needed for testing purposes.

Ideally, we will get rid of these heuristics entirely and instead introduce some sort of "side channel" that allows the portfile to record accesses -- such as by writing out a json document inside `vcpkg_from_github()` with the actual information.

If we do introduce another area that needs CMake parsing heuristics before we're able to delete them from the SPDX path, we can move them out into separate files at that point.

2024-04-15 22:57 UTC, ras0219-msft commented on src/vcpkg-test/cmake.cpp
> +        auto res = find_cmake_invocation("lorem_ipsum( )", "lorem_ipsum");
This should test additional edge cases:
1. `lorem_ipsum_`
2. `lorem_ipsum (`
3. `lorem_ipsum` (EOF)

2024-11-16 03:29 UTC, BillyONeal approved these changes

2024-11-16 03:35 UTC, BillyONeal commented on src/vcpkg/spdx.cpp
> -    if (ParserBase::is_word_char(*it)) return {};
@ras0219-msft I really don't understand the significance of these 'word char' checks here. If a file has `vcpkg_from_github .... vcpkg_from_git`, then we should skip over the first one and go to the real one, which I added a test for and fixed. Please double check that I did not misunderstand these' purpose.

2024-12-06 22:12 UTC, merged

2024-12-06 22:12 UTC, BillyONeal commented
@Thomas1664 Thanks for the fixes!