Suggest running `git pull` when a version is not found in the database.
microsoft/vcpkg-tool pull request #1479
Opened 2024-08-19 09:15 UTC by teo-tsirpanis

Might help diagnosing failures caused by an updated `builtin-baseline` and an outdated Git registry.

2024-08-19 13:17 UTC, autoantwort commented on include/vcpkg/base/message-data.inc.h
> +DECLARE_MESSAGE(ChecksUpdateVcpkg, (), "", "updating vcpkg by rerunning bootstrap-vcpkg or running `git pull` may resolve this failure.")
```suggestion
DECLARE_MESSAGE(ChecksUpdateVcpkg, (), "", "updating vcpkg by rerunning `git pull` and bootstrap-vcpkg may resolve this failure.")
```

2024-08-19 17:38 UTC, teo-tsirpanis commented on include/vcpkg/base/message-data.inc.h
> +DECLARE_MESSAGE(ChecksUpdateVcpkg, (), "", "updating vcpkg by rerunning bootstrap-vcpkg or running `git pull` may resolve this failure.")
Done.

2024-08-29 00:02 UTC, BillyONeal requested changes
Thanks for your contribution to vcpkg! Unfortunately I think there are some serious problems with this change:

1. The `ChecksUpdateVcpkg` message is used for several cases that are not 'baseline sha nonexistent'. In fact, the majority of cases where this is used won't be helped by a `git pull`. (For what it's worth, I strongly dislike the current message and have been campaigning to remove it entirely, but at least bootstrap-vcpkg won't accidentally change unrelated git repos and stuff)
2. The advice won't work if the current working directory isn't VCPKG_ROOT, or if the vcpkg copy is the one-liner install, or the one shipping with Visual Studio.
3. This won't do anything if the user isn't using the builtin registry.

I think this message needs to only be emitted when it would do something and needs tests.

2024-09-09 15:51 UTC, teo-tsirpanis commented
Thanks for the feedback. Let's keep the message as-is.

2024-09-09 15:51 UTC, closed without merging