upgrade: Make --keep-going the default
microsoft/vcpkg-tool pull request #308
Opened 2021-12-21 01:44 UTC by autoantwort

Closes [#17922](https://github.com/microsoft/vcpkg/discussions/17922)

2021-12-21 18:58 UTC, vkaytsanov approved these changes
Ship it

2021-12-29 19:22 UTC, strega-nil-ms commented
I like this choice; however, it definitely requires discussion.

2022-01-06 19:14 UTC, strega-nil-ms requested changes
Thanks, just some minor stuff.

2022-01-06 19:14 UTC, strega-nil-ms commented on src/vcpkg/commands.upgrade.cpp
> +        {OPTION_KEEP_GOING, "The default (deprecated)"},
```suggestion
        {OPTION_KEEP_GOING, "Continue installing packages on failure (default)"},
```

2022-01-06 19:14 UTC, strega-nil-ms commented on src/vcpkg/commands.upgrade.cpp
> +        {OPTION_STOP_AT_FAILURE, "Stop installing packages on failure"},
```suggestion
        {OPTION_NO_KEEP_GOING, "Stop installing packages on failure"},
```

2022-01-06 19:14 UTC, strega-nil-ms commented on src/vcpkg/commands.upgrade.cpp
> +
```suggestion
```

it's not standard practice to warn on passing the "default" for an option.

2022-01-06 19:14 UTC, strega-nil-ms commented on src/vcpkg/commands.upgrade.cpp
Also, make sure that you check for both `OPTION_KEEP_GOING` and `OPTION_NO_KEEP_GOING` and error if both are passed.

2022-01-06 19:14 UTC, strega-nil-ms commented on src/vcpkg/commands.upgrade.cpp
> +    static constexpr StringLiteral OPTION_STOP_AT_FAILURE = "stop-at-failure";
```suggestion
    static constexpr StringLiteral OPTION_NO_KEEP_GOING = "no-keep-going";
```

this is the standard.

2022-02-12 02:39 UTC, BillyONeal approved these changes

2022-02-18 00:50 UTC, strega-nil-ms approved these changes

2022-02-18 00:50 UTC, merged