Add SourceLink
microsoft/vcpkg-tool pull request #63
Opened 2021-04-16 15:45 UTC by frivard-coveo

This is a possible solution for improvement[ #17325 ](https://github.com/microsoft/vcpkg/issues/17325)

2021-04-16 15:47 UTC, frivard-coveo commented on .gitignore
> +/out
I added this because in Visual Studio 2019, the default output directory for CMake Projects is "out/build/{buildType}".

2021-04-19 21:21 UTC, strega-nil requested changes

2021-05-17 17:55 UTC, ras0219 approved these changes

2021-05-24 18:22 UTC, merged

2021-05-24 18:22 UTC, ras0219-msft commented
Thanks for the PR!