fix issue#28700; parens need to be shell-escaped on Linux
microsoft/vcpkg-tool pull request #862
Opened 2023-01-17 19:19 UTC by markle11m

2023-01-17 20:56 UTC, vicroms approved these changes

2023-01-18 21:04 UTC, BillyONeal requested changes
This change seems insufficient:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/1544943/213293397-543bb75b-e28d-4a1a-a804-1cba416350e7.png">

I think you need to add handling of `$` and \` (backtick) on line 86?

2023-01-18 21:05 UTC, BillyONeal commented
<img width="466" alt="image" src="https://user-images.githubusercontent.com/1544943/213294431-3f386b99-dac8-465b-8463-13419c66ab73.png">

2023-01-18 22:47 UTC, BillyONeal approved these changes
LGTM if PR Build comes back OK

2023-01-20 00:54 UTC, merged